---
title: "HouseCleaning"
author: "Kathryn Bryant"
date: "10/31/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r dataload}
house.test = read.csv("test.csv", stringsAsFactors = TRUE, na.strings = c("NA", ""))
house.train = read.csv("train.csv", stringsAsFactors = TRUE, na.strings = c("NA", ""))
house.test$SalePrice = 0
house = rbind(house.train, house.test)
```

```{r Alley}
levels(house$Alley)
```


```{r}
library(Amelia)
missmap(house, legend = TRUE, col = c("yellow","black"), main = "House Price Missing Data Map")
```
```{r}
sum(is.na(house$Alley))/nrow(house)
```
```{r}
str(house)
```

```{r}
num_vars = house[, sapply(house, is.numeric)]
num_vars = num_vars[,-1]
num_vars1 = num_vars[, 1:10]
plot(num_vars1, col = house$Alley)
```
```{r}
num_vars2 = num_vars[, 11:20]
plot(num_vars2, col = house$Alley)
```
```{r}
num_vars3 = num_vars[, 21:30]
plot(num_vars3, col = house$Alley)
```
```{r}
num_vars4 = num_vars[, 31:length(names(num_vars))]
plot(num_vars4, col = house$Alley)
```
```{r}
house$GarageFinish = as.character(house$GarageFinish)
house$GarageFinish[is.na(house$GarageFinish)] = 'NA'
house$GarageFinish = as.factor(house$GarageFinish)
levels(house$GarageFinish)
```
```{r}
house$GarageYrBlt = as.character(house$GarageYrBlt)
house$GarageYrBlt[is.na(house$GarageYrBlt)] = 'NA'
house$GarageYrBlt = as.factor(house$GarageYrBlt)
levels(house$GarageYrBlt)

# There is a problem with the second to last level here: we have a year of 2207. Will replace
# with 2007:

levels(house$GarageYrBlt)[103] = "2007"
levels(house$GarageYrBlt)
```

```{r}
house$GarageType = as.character(house$GarageType)
house$GarageType[is.na(house$GarageType)] = 'NA'
house$GarageType = as.factor(house$GarageType)
levels(house$GarageType)
```

```{r}
house$Alley = as.character(house$Alley)
house$Alley[is.na(house$Alley)] = 'NA'
house$Alley = as.factor(house$Alley)
levels(house$Alley)
```
```{r}
house$Fence = as.character(house$Fence)
house$Fence[is.na(house$Fence)] = 'NA'
house$Fence = as.factor(house$Fence)
levels(house$Fence)
```
```{r}
house$BsmtExposure = as.character(house$BsmtExposure)
house$BsmtExposure[is.na(house$BsmtExposure)] = 'NA'
house$BsmtExposure = as.factor(house$BsmtExposure)
#levels(house$BsmtExposure)
```

```{r}
house$BsmtCond = as.character(house$BsmtCond)
house$BsmtCond[is.na(house$BsmtCond)] = 'NA'
house$BsmtCond = as.factor(house$BsmtCond)
levels(house$BsmtCond)
```

```{r}
house$BsmtQual = as.character(house$BsmtQual)
house$BsmtQual[is.na(house$BsmtQual)] = 'NA'
house$BsmtQual = as.factor(house$BsmtQual)
levels(house$BsmtQual)
```

```{r}
house$BsmtFinType1 = as.character(house$BsmtFinType1)
house$BsmtFinType1[is.na(house$BsmtFinType1)] = 'NA'
house$BsmtFinType1 = as.factor(house$BsmtFinType1)
levels(house$BsmtFinType1)
```
```{r}
house$BsmtFinType2 = as.character(house$BsmtFinType2)
house$BsmtFinType2[is.na(house$BsmtFinType2)] = 'NA'
house$BsmtFinType2 = as.factor(house$BsmtFinType2)
levels(house$BsmtFinType2)
```
```{r}
house$FireplaceQu = as.character(house$FireplaceQu)
house$FireplaceQu[is.na(house$FireplaceQu)] = 'NA'
house$FireplaceQu = as.factor(house$FireplaceQu)
levels(house$FireplaceQu)
```

```{r}
house$MiscFeature = as.character(house$MiscFeature)
house$MiscFeature[is.na(house$MiscFeature)] = 'NA'
house$MiscFeature = as.factor(house$MiscFeature)
levels(house$MiscFeature)
```

```{r}
house$PoolQC = as.character(house$PoolQC)
house$PoolQC[is.na(house$PoolQC)] = 'NA'
house$PoolQC = as.factor(house$PoolQC)
levels(house$PoolQC)
```
```{r include=FALSE}
library(dplyr)
lot.info = house %>% select(LotFrontage, LotConfig, LotArea, LotShape)
lf.missing = lot.info[is.na(lot.info$LotFrontage),]
group_by(lf.missing, LotConfig) %>% summarise(count = n())
```

